services:
  solr:
    image: solr:9.8
    container_name: solr_server
    restart: always
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/var/solr/data
      - ./security.json:/var/solr/data/security.json
    environment:
      SOLR_JAVA_MEM: "-Xms512m -Xmx2g"
      SOLR_OPTS: "-Dbasicauth=myuser:mypass"
      SOLR_LOG_LEVEL: "INFO"
      SOLR_SSL_ENABLED: "false"
    networks:
      - solr_network

volumes:
  solr_data:

networks:
  solr_network:
    driver: bridge
